# Generated by Django 5.1.3 on 2024-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='posts/', verbose_name='Файл (не обязательно)'),
        ),
    ]
